spring:
  application:
    name: room-reservation-api
  sql:
    init:
      mode: always
  data:
    web:
      pageable:
        serialization-mode: via_dto
  web:
    resources:
      add-mappings: false
#logging:
#  level:
#    org.springframework.web: trace
#    org.springframework.data: trace
